### ISSUE TITLE
Publish release with updated hyper-openssl

### ISSUE THREAD

**Issue by blakehawkins** [eeeeeta/glitch-in-the-matrix#13]
`master` has hyper-openssl 0.7, but the current release on crates.io is quite outdated with 0.3.

`master` is compiling just fine, and this update improves openssl compatibility.

Please can you `cargo publish` a patch release?

**Comment by eeeeeta** [comment]
I played around with this for a bit, and it doesn't look like it's as simple as
just bumping the version (and requires more advanced fiddling to update all the
crates to somewhat modern versions). Since this library is effectively
unmaintained, it's unlikely I'll get around to doing that any time soon;
however, I'd be more than welcome to merge a PR with this change, and publish a
new release for that!

**Comment by blakehawkins** [comment]
Hey @eeeeeta sorry if this wasn't clear before. I've also had a play around, and found that the current develop branch for `glitch-in-the-matrix` is working just fine (it has significant updates versus the current published version).

It would be great if you could simply cut a release from the current develop branch 👍 

By the way, I'm now using this in "production" - https://github.com/blakehawkins/crate_glitch/blob/master/Cargo.toml#L15

**Comment by blakehawkins** [comment]
Hey @eeeeeta did you see my comment above?

I wonder if you can publish a `pre-release`, i.e. `0.14.0-rc1` off of `develop`

Cheers,

**Comment by eeeeeta** [comment]
I'm really sorry @blakehawkins -- I've been somewhat snowed under recently and this got buried under a whole bunch of other things in my inbox...! If you're still interested in my cutting a prerelease, I can have one done for you by the end of tomorrow -- but as I've just told someone else in https://github.com/matrix-org/matrix-ircd/pull/54#issuecomment-596780348, you might well be better off looking for an alternative library that's better maintained. If you still want me to cut a release though, just let me know and I'll do it!

**Comment by blakehawkins** [comment]
@eeeeeta no worries! Please do cut a release - I need it to publish my dependent projects to crates.io

Thanks for your work on this project!

**Comment by eeeeeta** [comment]
@blakehawkins I've just published `0.14.0` on crates.io; going to close this now. Let me know if it didn't work for some reason!

**Comment by blakehawkins** [comment]
Hey @eeeeeta 

Thanks very much!

I'm sorry for not specifying this before, but I think a new release of gm-types is also needed in order to use `0.14.0`. Do you think you could release a compatible version to crates.io as well?

Cheers!

https://github.com/eeeeeta/glitch-in-the-matrix/tree/develop/gm-types

**Comment by eeeeeta** [comment]
@blakehawkins I thought I did: https://crates.io/crates/gm-types/0.4.0-pre

**Comment by blakehawkins** [comment]
Hey @eeeeeta thanks! Yes it works.

Thanks again for all your work on this project. Releasing 0.14.0 and 0.4.0-pre enabled me to publish my projects:

https://crates.io/crates/crate_glitch

https://crates.io/crates/send_glitch

Cheers,
