### ISSUE TITLE
Latest version has critical dependabot alerts

### ISSUE THREAD

**Issue by blakehawkins** [eeeeeta/glitch-in-the-matrix#15]
gitm 0.14 uses an outdated version of hyper that transitively depends on a version of smallvec with a critical CVE

It would be good to add a note that folks should use official maintained crates if there's no plan to make another release here

**Comment by eeeeeta** [comment]
The README already states that you shouldn't use this in production, and has done since the project was created... (also, it hasn't been touched in 3 years!) I guess I'll archive the repo to make it even clearer :p
