### ISSUE TITLE
State keys

### ISSUE THREAD

**Issue by elinorbgr** [eeeeeta/glitch-in-the-matrix#4]
It'd be useful to have some method to send state events, modifying the state of the room.

My usecase is for a bot that would store its state directly into the room, allowing the program itself to be completely stateless.

**Comment by eeeeeta** [comment]
Hi, sorry for the 21-day delay in responding - but this should be doable now, with version 0.8.1 (see `RoomClient::get_state` and `RoomClient::set_state`)! It hasn't been tested though, so file bug reports if it breaks.
